### ISSUE TITLE
Data Output

### ISSUE THREAD

**Issue by Col168** [Precision-Technologies-Ltd/master-gauge-issues#4]
After entering the basic data & pressing view
The figure in brackets next to the module, what is this? Though it was the DP or diametral pitch, but its not. I would suggest this is removed
Next to the pressure angle (in brackets) you have the degrees, minutes & seconds values. Can you change the symbols please as they are showing as degrees, seconds then minutes (just a typo)
![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146350782/414d2432-6ab6-448f-9050-b17bf90e646c)

**Comment by inyoka** [comment]
Great thank you.  This has been fixed in the next version.

[Link to fix in code](https://github.com/Precision-Technologies-Ltd/master-gauge/commit/71fd4829cd983af3d2146e7c167a6463dc172499)
![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/8c7d1555-adfa-46d6-b062-06f6030bb6c7)
