### ISSUE TITLE
Helical Gear - DOP from DOP, Pin Dia & New DOP

### ISSUE THREAD

**Issue by JB-1956** [Precision-Technologies-Ltd/master-gauge-issues#9]
Hi,

Getting a discrepancy when calculating a new DOP with an alternative pin size, from the original DOP & pin size;

Gear Details:
100 T
1.855 Mod
21° Pressure Angle
28 ° Helix Angle

Results given from DOS Program:
Old Pin Ø: 3.25
Old DOP: 213.3469

Alt Pin Ø: 3.5
Alt DOP: 214.2885

Results given from master-gauge:
Old Pin Ø: 3.25
Old DOP: 213.3469

Alt Pin Ø: 3.5
Alt DOP: 244.2882

![1 - Dop from, Pin Dia   New Pin Dia](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146351525/c2234830-f905-4473-9947-27442faeb091)

**Comment by inyoka** [comment]
This should be fixed in the next version, thank you for the report.  - Simon

https://github.com/Precision-Technologies-Ltd/master-gauge/commit/0215bb56cb03aaf6713b4b454ef9f19adce74e9c

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/0998eb56-ef04-4fb9-b14b-6b2a5f6638c6)
